package com.example.aibpmn.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.*;

/**
 * Validates BPMN Moddle JSON generated by AI
 * Ensures BPMN 2.0 compliance and semantic correctness
 */
@Service
public class BpmnValidationService {
    
    private static final Logger log = LoggerFactory.getLogger(BpmnValidationService.class);
    private final ObjectMapper objectMapper;
    
    public BpmnValidationService(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }
    
    public ValidationResult validate(String bpmnModdleJson) {
        List<String> errors = new ArrayList<>();
        List<String> warnings = new ArrayList<>();
        
        try {
            JsonNode bpmn = objectMapper.readTree(bpmnModdleJson);
            
            // 1. Validate root structure
            if (!validateRootStructure(bpmn, errors)) {
                return ValidationResult.invalid(errors, warnings);
            }
            
            // 2. Validate processes
            JsonNode rootElements = bpmn.get("rootElements");
            for (JsonNode element : rootElements) {
                if ("bpmn:Process".equals(element.get("$type").asText())) {
                    validateProcess(element, errors, warnings);
                }
            }
            
            // 3. Check for common issues
            checkCommonIssues(bpmn, warnings);
            
            if (errors.isEmpty()) {
                log.info("BPMN validation passed with {} warnings", warnings.size());
                return ValidationResult.valid(warnings);
            } else {
                log.warn("BPMN validation failed with {} errors", errors.size());
                return ValidationResult.invalid(errors, warnings);
            }
            
        } catch (JsonProcessingException e) {
            errors.add("Invalid JSON format: " + e.getMessage());
            return ValidationResult.invalid(errors, warnings);
        }
    }
    
    private boolean validateRootStructure(JsonNode bpmn, List<String> errors) {
        if (!bpmn.has("$type")) {
            errors.add("Missing $type field");
            return false;
        }
        
        if (!"bpmn:Definitions".equals(bpmn.get("$type").asText())) {
            errors.add("Root element must be bpmn:Definitions");
            return false;
        }
        
        if (!bpmn.has("rootElements") || bpmn.get("rootElements").size() == 0) {
            errors.add("No root elements (processes) found");
            return false;
        }
        
        return true;
    }
    
    private void validateProcess(JsonNode process, List<String> errors, List<String> warnings) {
        JsonNode flowElements = process.get("flowElements");
        
        if (flowElements == null || flowElements.size() == 0) {
            errors.add("Process has no flow elements");
            return;
        }
        
        // Check for start event
        boolean hasStart = false;
        boolean hasEnd = false;
        Set<String> elementIds = new HashSet<>();
        Map<String, List<String>> incomingMap = new HashMap<>();
        Map<String, List<String>> outgoingMap = new HashMap<>();
        
        for (JsonNode element : flowElements) {
            String type = element.get("$type").asText();
            String id = element.get("id").asText();
            
            // Check for duplicates
            if (elementIds.contains(id)) {
                errors.add("Duplicate element ID: " + id);
            }
            elementIds.add(id);
            
            // Check for start/end events
            if (type.equals("bpmn:StartEvent")) hasStart = true;
            if (type.equals("bpmn:EndEvent")) hasEnd = true;
            
            // Build connection maps
            if (element.has("incoming")) {
                incomingMap.put(id, jsonArrayToList(element.get("incoming")));
            }
            if (element.has("outgoing")) {
                outgoingMap.put(id, jsonArrayToList(element.get("outgoing")));
            }
        }
        
        if (!hasStart) {
            errors.add("Process must have at least one Start Event");
        }
        
        if (!hasEnd) {
            errors.add("Process must have at least one End Event");
        }
        
        // Check for orphan nodes (no incoming and no outgoing)
        for (String id : elementIds) {
            if (!isStartOrEndEvent(process, id)) {
                boolean hasIncoming = incomingMap.containsKey(id) && 
                                     !incomingMap.get(id).isEmpty();
                boolean hasOutgoing = outgoingMap.containsKey(id) && 
                                     !outgoingMap.get(id).isEmpty();
                
                if (!hasIncoming && !hasOutgoing) {
                    warnings.add("Orphan element (not connected): " + id);
                }
            }
        }
        
        // Validate sequence flows
        for (JsonNode element : flowElements) {
            if ("bpmn:SequenceFlow".equals(element.get("$type").asText())) {
                validateSequenceFlow(element, elementIds, errors);
            }
        }
    }
    
    private void validateSequenceFlow(JsonNode flow, Set<String> validIds, List<String> errors) {
        String flowId = flow.get("id").asText();
        
        if (!flow.has("sourceRef")) {
            errors.add("SequenceFlow " + flowId + " missing sourceRef");
            return;
        }
        
        if (!flow.has("targetRef")) {
            errors.add("SequenceFlow " + flowId + " missing targetRef");
            return;
        }
        
        String sourceRef = flow.get("sourceRef").asText();
        String targetRef = flow.get("targetRef").asText();
        
        if (!validIds.contains(sourceRef)) {
            errors.add("SequenceFlow " + flowId + " references non-existent source: " + sourceRef);
        }
        
        if (!validIds.contains(targetRef)) {
            errors.add("SequenceFlow " + flowId + " references non-existent target: " + targetRef);
        }
    }
    
    private void checkCommonIssues(JsonNode bpmn, List<String> warnings) {
        // Check for tasks without names
        // Check for gateways without conditions on outgoing flows
        // etc.
    }
    
    private List<String> jsonArrayToList(JsonNode arrayNode) {
        List<String> list = new ArrayList<>();
        if (arrayNode != null && arrayNode.isArray()) {
            arrayNode.forEach(node -> list.add(node.asText()));
        }
        return list;
    }
    
    private boolean isStartOrEndEvent(JsonNode process, String elementId) {
        JsonNode flowElements = process.get("flowElements");
        for (JsonNode element : flowElements) {
            if (element.get("id").asText().equals(elementId)) {
                String type = element.get("$type").asText();
                return type.equals("bpmn:StartEvent") || type.equals("bpmn:EndEvent");
            }
        }
        return false;
    }
}
